# Generated by Django 4.0.5 on 2022-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleofblog', models.CharField(max_length=200)),
                ('categoryofblog', models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid19', 'Covid19'), ('Immunization ', 'Immunization ')], max_length=200)),
                ('summaryofblog', models.TextField()),
                ('contentofblog', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('blogpic', models.ImageField(upload_to='blogpic')),
            ],
        ),
    ]
