# Generated by Django 4.0.5 on 2022-06-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='BlogForm',
        ),
    ]
