# Generated by Django 4.0.5 on 2022-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_blogform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogform',
            name='categoryofblog',
            field=models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid19', 'Covid19'), ('Immunization', 'Immunization')], max_length=200),
        ),
    ]
